"""
VaxAssist AI - Authoritative Development Seed & Cleanup Script (Phase A)
Safely purges obsolete test accounts/records and creates a consistent, realistic Indian demo dataset.

DEMO DATASET:
- Family Name: Sharma Family (Mumbai, Maharashtra)
- Primary User: Rajesh Sharma (rajesh.sharma@vaxassist.demo)
- Healthcare Workers: Dr. Anjali Deshmukh (Lilavati Hospital), Dr. Vikram Patil (KEM Hospital)
- Admin: Sunita Rao (admin@vaxassist.demo)
"""

import os
import sys
import asyncio
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from motor.motor_asyncio import AsyncIOMotorClient
import chromadb

# Ensure backend root is on sys.path
backend_dir = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(backend_dir))

from app.config import settings
from app.utils.security import hash_password
from app.models.user import UserRole, AccountStatus
from app.models.vaccination import VaccinationStatus, VaccineCategory
from app.models.notification import (
    NotificationChannel,
    NotificationType,
    NotificationPriority,
    NotificationStatus,
)

DEMO_PASSWORDS = {
    "patient": "Rajesh@Vax2026!",
    "hcw1": "DrAnjali@Vax2026!",
    "hcw2": "DrVikram@Vax2026!",
    "admin": "Admin@Vax2026!",
}


async def seed_database():
    print("=" * 75)
    print("VAXASSIST AI — PHASE A DEMO DATA INITIALIZATION & CLEANUP")
    print("=" * 75)

    # 1. Environment Safety Check
    if settings.ENVIRONMENT != "development":
        print(f"ABORT: Cannot run seed script in non-development environment '{settings.ENVIRONMENT}'!")
        sys.exit(1)

    print(f"Connecting to MongoDB: {settings.MONGODB_DB_NAME}...")
    client = AsyncIOMotorClient(settings.MONGODB_URI)
    db = client[settings.MONGODB_DB_NAME]

    # Test connection
    try:
        await client.admin.command("ping")
        print("MongoDB connection verified successfully.")
    except Exception as e:
        print(f"Failed to connect to MongoDB: {e}")
        sys.exit(1)

    # 2. Cleanup Obsolete Mock & Test Data
    print("\n--- 1. Cleaning Obsolete Test Records ---")
    
    # Identify legacy test users (e.g. autogenerated test accounts)
    test_user_filter = {
        "$or": [
            {"email": {"$regex": r"^patient_\d+@"}},
            {"email": {"$regex": r"^dr_smith_\d+@"}},
            {"email": {"$regex": r"^vax_patient_"}},
            {"email": {"$regex": r"^patient_[ab]_\d+@"}},
            {"email": "pradeep@gmail.com"},
        ]
    }
    
    old_users = await db.users.find(test_user_filter, {"_id": 1, "email": 1}).to_list(length=500)
    old_user_ids = [str(u["_id"]) for u in old_users]
    
    if old_user_ids:
        # Delete old users
        res_users = await db.users.delete_many({"_id": {"$in": [u["_id"] for u in old_users]}})
        print(f"  Removed {res_users.deleted_count} obsolete test user accounts.")
        
        # Delete families belonging to old users
        res_fams = await db.families.delete_many({"owner_user_id": {"$in": old_user_ids}})
        print(f"  Removed {res_fams.deleted_count} obsolete test families.")
        
        # Clean obsolete notifications
        res_notifs = await db.notifications.delete_many({"user_id": {"$in": old_user_ids}})
        print(f"  Removed {res_notifs.deleted_count} obsolete test notifications.")
        
        # Clean obsolete preferences
        res_prefs = await db.notification_preferences.delete_many({"user_id": {"$in": old_user_ids}})
        print(f"  Removed {res_prefs.deleted_count} obsolete test preferences.")
    else:
        print("  No obsolete autogenerated test users found.")

    # 3. Clean ChromaDB Test Collections / Chunks
    print("\n--- 2. Cleaning ChromaDB Knowledge Vectors ---")
    try:
        chroma_path = Path(settings.CHROMA_PERSIST_DIRECTORY)
        if chroma_path.exists():
            chroma_client = chromadb.PersistentClient(path=str(chroma_path))
            try:
                coll = chroma_client.get_collection(settings.CHROMA_COLLECTION_NAME)
                # Check for test documents
                test_doc_ids = []
                data = coll.get()
                for doc_id, meta in zip(data["ids"], data["metadatas"]):
                    if "Test" in meta.get("document_title", ""):
                        test_doc_ids.append(doc_id)
                if test_doc_ids:
                    coll.delete(ids=test_doc_ids)
                    print(f"  Removed {len(test_doc_ids)} test vector chunks from ChromaDB '{coll.name}'.")
                else:
                    print(f"  ChromaDB collection '{coll.name}' has {coll.count()} authentic vectors.")
            except Exception as e:
                print(f"  ChromaDB collection notice: {e}")
        # Clean test knowledge documents in MongoDB
        res_kdocs = await db.knowledge_documents.delete_many({"title": {"$regex": r"Test \d+"}})
        if res_kdocs.deleted_count > 0:
            print(f"  Removed {res_kdocs.deleted_count} test knowledge document metadata entries in MongoDB.")
    except Exception as e:
        print(f"  ChromaDB cleanup notice: {e}")

    # 4. Seed Demo Users (Admin, Healthcare Workers, Patient)
    print("\n--- 3. Seeding Realistic Demo User Accounts ---")
    now_utc = datetime.now(timezone.utc)

    # A. System Administrator
    admin_email = "admin@vaxassist.demo"
    admin_doc = {
        "name": "Sunita Rao",
        "email": admin_email,
        "hashed_password": hash_password(DEMO_PASSWORDS["admin"]),
        "role": UserRole.ADMIN.value,
        "account_status": AccountStatus.ACTIVE.value,
        "clinic_or_hospital": "Ministry of Health & Family Welfare / State Immunization HQ",
        "created_at": now_utc,
        "updated_at": now_utc,
    }
    await db.users.update_one({"email": admin_email}, {"$set": admin_doc}, upsert=True)
    admin_user = await db.users.find_one({"email": admin_email})
    admin_id = str(admin_user["_id"])
    print(f"  [ADMIN] {admin_doc['name']} ({admin_email}) -> ID: {admin_id}")

    # B. Healthcare Worker 1 (Lilavati Hospital)
    hcw1_email = "dr.anjali.deshmukh@vaxassist.demo"
    hcw1_doc = {
        "name": "Dr. Anjali Deshmukh",
        "email": hcw1_email,
        "hashed_password": hash_password(DEMO_PASSWORDS["hcw1"]),
        "role": UserRole.HEALTHCARE_WORKER.value,
        "account_status": AccountStatus.ACTIVE.value,
        "license_number": "MMC-2012-08492",
        "clinic_or_hospital": "Lilavati Hospital & Research Centre, Bandra West, Mumbai",
        "created_at": now_utc,
        "updated_at": now_utc,
    }
    await db.users.update_one({"email": hcw1_email}, {"$set": hcw1_doc}, upsert=True)
    hcw1_user = await db.users.find_one({"email": hcw1_email})
    hcw1_id = str(hcw1_user["_id"])
    print(f"  [HCW 1] {hcw1_doc['name']} ({hcw1_email}) -> ID: {hcw1_id}")

    # C. Healthcare Worker 2 (KEM Hospital)
    hcw2_email = "dr.vikram.patil@vaxassist.demo"
    hcw2_doc = {
        "name": "Dr. Vikram Patil",
        "email": hcw2_email,
        "hashed_password": hash_password(DEMO_PASSWORDS["hcw2"]),
        "role": UserRole.HEALTHCARE_WORKER.value,
        "account_status": AccountStatus.ACTIVE.value,
        "license_number": "MMC-2008-01234",
        "clinic_or_hospital": "King Edward Memorial (KEM) Hospital, Parel, Mumbai",
        "created_at": now_utc,
        "updated_at": now_utc,
    }
    await db.users.update_one({"email": hcw2_email}, {"$set": hcw2_doc}, upsert=True)
    hcw2_user = await db.users.find_one({"email": hcw2_email})
    hcw2_id = str(hcw2_user["_id"])
    print(f"  [HCW 2] {hcw2_doc['name']} ({hcw2_email}) -> ID: {hcw2_id}")

    # D. Patient / Family Administrator (Rajesh Sharma)
    patient_email = "rajesh.sharma@vaxassist.demo"
    patient_doc = {
        "name": "Rajesh Sharma",
        "email": patient_email,
        "hashed_password": hash_password(DEMO_PASSWORDS["patient"]),
        "role": UserRole.PATIENT.value,
        "account_status": AccountStatus.ACTIVE.value,
        "created_at": now_utc,
        "updated_at": now_utc,
    }
    await db.users.update_one({"email": patient_email}, {"$set": patient_doc}, upsert=True)
    patient_user = await db.users.find_one({"email": patient_email})
    patient_id = str(patient_user["_id"])
    print(f"  [PATIENT] {patient_doc['name']} ({patient_email}) -> ID: {patient_id}")

    # 5. Seed Family Household
    print("\n--- 4. Seeding Realistic Indian Family (Sharma Family, Mumbai) ---")
    family_filter = {"owner_user_id": patient_id}
    family_data = {
        "family_name": "Sharma Household",
        "owner_user_id": patient_id,
        "description": "Flat 402, Sea Green Apartments, Perry Cross Road, Bandra West, Mumbai, Maharashtra 400050",
        "created_at": now_utc,
        "updated_at": now_utc,
    }
    await db.families.update_one(family_filter, {"$set": family_data}, upsert=True)
    family_record = await db.families.find_one(family_filter)
    family_id = str(family_record["_id"])
    print(f"  Family: '{family_data['family_name']}' -> ID: {family_id}")

    # 6. Seed Family Members with Realistic Indian Profiles
    members_to_seed = [
        {
            "family_id": family_id,
            "full_name": "Rajesh Sharma",
            "date_of_birth": datetime(1988, 4, 15),
            "gender": "MALE",
            "relationship": "SELF",
            "blood_group": "O+",
            "allergies": [],
            "notes": "Primary account holder. Works in financial services. No chronic conditions.",
        },
        {
            "family_id": family_id,
            "full_name": "Pooja Sharma",
            "date_of_birth": datetime(1991, 8, 22),
            "gender": "FEMALE",
            "relationship": "SPOUSE",
            "blood_group": "A+",
            "allergies": ["Sulfonamides"],
            "notes": "Mother. Mild sulfa allergy documented.",
        },
        {
            "family_id": family_id,
            "full_name": "Aarav Sharma",
            "date_of_birth": datetime(2020, 7, 10),
            "gender": "MALE",
            "relationship": "CHILD",
            "blood_group": "O+",
            "allergies": [],
            "notes": "Son (Age 6). Primary NIS series completed in infancy. DPT Booster 2 due for school milestone.",
        },
        {
            "family_id": family_id,
            "full_name": "Ananya Sharma",
            "date_of_birth": datetime(2026, 5, 18),
            "gender": "FEMALE",
            "relationship": "CHILD",
            "blood_group": "B+",
            "allergies": [],
            "notes": "Infant daughter (~4 months). Birth, 6-week, and 10-week doses completed. 14-week doses due/catch-up.",
        },
        {
            "family_id": family_id,
            "full_name": "Ramesh Sharma",
            "date_of_birth": datetime(1958, 1, 12),
            "gender": "MALE",
            "relationship": "PARENT",
            "blood_group": "B+",
            "allergies": ["Penicillin"],
            "notes": "Grandfather (Age 68). Senior citizen health surveillance. Penicillin allergy.",
        },
    ]

    member_ids = {}
    for m in members_to_seed:
        m["created_at"] = now_utc
        m["updated_at"] = now_utc
        query = {"family_id": family_id, "full_name": m["full_name"]}
        await db.family_members.update_one(query, {"$set": m}, upsert=True)
        rec = await db.family_members.find_one(query)
        mid = str(rec["_id"])
        member_ids[m["full_name"]] = mid
        age_years = (datetime.now() - m["date_of_birth"]).days // 365
        print(f"  Member: {m['full_name']} ({m['relationship']}, {age_years} yrs, DOB {m['date_of_birth'].strftime('%Y-%m-%d')}) -> ID: {mid}")

    # 7. Seed Authentic UIP / NIS Vaccination Records
    print("\n--- 5. Seeding Authentic Indian UIP Vaccination Records ---")
    # Clean previous records for this family
    fids = list(member_ids.values())
    await db.vaccination_records.delete_many({"family_member_id": {"$in": fids}})

    vaccination_records = [
        # -------------------------------------------------------------
        # AARAV SHARMA (Age 6, DOB 2020-07-10) — Primary childhood doses completed
        # -------------------------------------------------------------
        {
            "family_member_id": member_ids["Aarav Sharma"],
            "vaccine_code": "BCG",
            "vaccine_name": "Bacillus Calmette-Guérin (BCG)",
            "dose_number": 1,
            "dose_name": "Birth Dose",
            "administered_date": datetime(2020, 7, 11),
            "administered_by": "Dr. Anjali Deshmukh",
            "healthcare_provider": "Lilavati Hospital & Research Centre, Mumbai",
            "batch_number": "BCG-2020-091",
            "vaccination_status": VaccinationStatus.COMPLETED.value,
            "is_verified": True,
            "notes": "Normal intradermal wheal observed, left deltoid. Scar verified at 12 weeks.",
        },
        {
            "family_member_id": member_ids["Aarav Sharma"],
            "vaccine_code": "HEPB",
            "vaccine_name": "Hepatitis B (Birth Dose)",
            "dose_number": 1,
            "dose_name": "Birth Dose",
            "administered_date": datetime(2020, 7, 11),
            "administered_by": "Dr. Anjali Deshmukh",
            "healthcare_provider": "Lilavati Hospital & Research Centre, Mumbai",
            "batch_number": "HB-2020-112",
            "vaccination_status": VaccinationStatus.COMPLETED.value,
            "is_verified": True,
            "notes": "Administered within 24 hours of birth.",
        },
        {
            "family_member_id": member_ids["Aarav Sharma"],
            "vaccine_code": "OPV",
            "vaccine_name": "Oral Polio Vaccine (OPV-0)",
            "dose_number": 1,
            "dose_name": "Birth Dose (OPV-0)",
            "administered_date": datetime(2020, 7, 11),
            "administered_by": "Dr. Anjali Deshmukh",
            "healthcare_provider": "Lilavati Hospital & Research Centre, Mumbai",
            "batch_number": "OPV-2020-043",
            "vaccination_status": VaccinationStatus.COMPLETED.value,
            "is_verified": True,
            "notes": "2 drops oral, well tolerated.",
        },
        {
            "family_member_id": member_ids["Aarav Sharma"],
            "vaccine_code": "PENTA",
            "vaccine_name": "Pentavalent (DTP-HepB-Hib 1)",
            "dose_number": 1,
            "dose_name": "6 Weeks (Dose 1)",
            "administered_date": datetime(2020, 8, 22),
            "administered_by": "Dr. Anjali Deshmukh",
            "healthcare_provider": "Lilavati Hospital & Research Centre, Mumbai",
            "batch_number": "PNT-2020-412",
            "vaccination_status": VaccinationStatus.COMPLETED.value,
            "is_verified": True,
        },
        {
            "family_member_id": member_ids["Aarav Sharma"],
            "vaccine_code": "PENTA",
            "vaccine_name": "Pentavalent (DTP-HepB-Hib 2)",
            "dose_number": 2,
            "dose_name": "10 Weeks (Dose 2)",
            "administered_date": datetime(2020, 9, 19),
            "administered_by": "Dr. Anjali Deshmukh",
            "healthcare_provider": "Lilavati Hospital & Research Centre, Mumbai",
            "batch_number": "PNT-2020-771",
            "vaccination_status": VaccinationStatus.COMPLETED.value,
            "is_verified": True,
        },
        {
            "family_member_id": member_ids["Aarav Sharma"],
            "vaccine_code": "PENTA",
            "vaccine_name": "Pentavalent (DTP-HepB-Hib 3)",
            "dose_number": 3,
            "dose_name": "14 Weeks (Dose 3)",
            "administered_date": datetime(2020, 10, 17),
            "administered_by": "Dr. Anjali Deshmukh",
            "healthcare_provider": "Lilavati Hospital & Research Centre, Mumbai",
            "batch_number": "PNT-2020-994",
            "vaccination_status": VaccinationStatus.COMPLETED.value,
            "is_verified": True,
        },
        {
            "family_member_id": member_ids["Aarav Sharma"],
            "vaccine_code": "MR",
            "vaccine_name": "Measles-Rubella (MR - Dose 1)",
            "dose_number": 1,
            "dose_name": "9-12 Months (Dose 1)",
            "administered_date": datetime(2021, 4, 15),
            "administered_by": "Dr. Anjali Deshmukh",
            "healthcare_provider": "Lilavati Hospital & Research Centre, Mumbai",
            "batch_number": "MR-2021-318",
            "vaccination_status": VaccinationStatus.COMPLETED.value,
            "is_verified": True,
        },
        {
            "family_member_id": member_ids["Aarav Sharma"],
            "vaccine_code": "MR",
            "vaccine_name": "Measles-Rubella (MR - Dose 2)",
            "dose_number": 2,
            "dose_name": "16-24 Months (Dose 2)",
            "administered_date": datetime(2022, 1, 20),
            "administered_by": "Dr. Anjali Deshmukh",
            "healthcare_provider": "Lilavati Hospital & Research Centre, Mumbai",
            "batch_number": "MR-2022-004",
            "vaccination_status": VaccinationStatus.COMPLETED.value,
            "is_verified": True,
        },
        {
            "family_member_id": member_ids["Aarav Sharma"],
            "vaccine_code": "DPT_BOOSTER",
            "vaccine_name": "DPT Booster 1",
            "dose_number": 1,
            "dose_name": "16-24 Months (Booster 1)",
            "administered_date": datetime(2022, 1, 20),
            "administered_by": "Dr. Anjali Deshmukh",
            "healthcare_provider": "Lilavati Hospital & Research Centre, Mumbai",
            "batch_number": "DPT-2022-108",
            "vaccination_status": VaccinationStatus.COMPLETED.value,
            "is_verified": True,
        },

        # -------------------------------------------------------------
        # ANANYA SHARMA (Infant ~4 months, DOB 2026-05-18)
        # -------------------------------------------------------------
        {
            "family_member_id": member_ids["Ananya Sharma"],
            "vaccine_code": "BCG",
            "vaccine_name": "Bacillus Calmette-Guérin (BCG)",
            "dose_number": 1,
            "dose_name": "Birth Dose",
            "administered_date": datetime(2026, 5, 19),
            "administered_by": "Dr. Anjali Deshmukh",
            "healthcare_provider": "Lilavati Hospital & Research Centre, Mumbai",
            "batch_number": "BCG-2026-B102",
            "vaccination_status": VaccinationStatus.COMPLETED.value,
            "is_verified": True,
            "notes": "Administered 24 hours post-delivery, left upper arm.",
        },
        {
            "family_member_id": member_ids["Ananya Sharma"],
            "vaccine_code": "HEPB",
            "vaccine_name": "Hepatitis B (Birth Dose)",
            "dose_number": 1,
            "dose_name": "Birth Dose",
            "administered_date": datetime(2026, 5, 19),
            "administered_by": "Dr. Anjali Deshmukh",
            "healthcare_provider": "Lilavati Hospital & Research Centre, Mumbai",
            "batch_number": "HB-2026-B812",
            "vaccination_status": VaccinationStatus.COMPLETED.value,
            "is_verified": True,
            "notes": "Intramuscular, anterolateral aspect of mid-thigh.",
        },
        {
            "family_member_id": member_ids["Ananya Sharma"],
            "vaccine_code": "OPV",
            "vaccine_name": "Oral Polio Vaccine (OPV-0)",
            "dose_number": 1,
            "dose_name": "Birth Dose",
            "administered_date": datetime(2026, 5, 19),
            "administered_by": "Dr. Anjali Deshmukh",
            "healthcare_provider": "Lilavati Hospital & Research Centre, Mumbai",
            "batch_number": "OPV-2026-012",
            "vaccination_status": VaccinationStatus.COMPLETED.value,
            "is_verified": True,
        },
        {
            "family_member_id": member_ids["Ananya Sharma"],
            "vaccine_code": "PENTA",
            "vaccine_name": "Pentavalent (DTP-HepB-Hib 1)",
            "dose_number": 1,
            "dose_name": "6 Weeks (Dose 1)",
            "administered_date": datetime(2026, 6, 29),
            "administered_by": "Dr. Anjali Deshmukh",
            "healthcare_provider": "Lilavati Hospital & Research Centre, Mumbai",
            "batch_number": "PNT-2026-092",
            "vaccination_status": VaccinationStatus.COMPLETED.value,
            "is_verified": True,
        },
        {
            "family_member_id": member_ids["Ananya Sharma"],
            "vaccine_code": "OPV",
            "vaccine_name": "Oral Polio Vaccine (OPV-1)",
            "dose_number": 2,
            "dose_name": "6 Weeks (OPV-1)",
            "administered_date": datetime(2026, 6, 29),
            "administered_by": "Dr. Anjali Deshmukh",
            "healthcare_provider": "Lilavati Hospital & Research Centre, Mumbai",
            "batch_number": "OPV-2026-141",
            "vaccination_status": VaccinationStatus.COMPLETED.value,
            "is_verified": True,
        },
        {
            "family_member_id": member_ids["Ananya Sharma"],
            "vaccine_code": "ROTA",
            "vaccine_name": "Rotavirus (RV-1)",
            "dose_number": 1,
            "dose_name": "6 Weeks (Dose 1)",
            "administered_date": datetime(2026, 6, 29),
            "administered_by": "Dr. Anjali Deshmukh",
            "healthcare_provider": "Lilavati Hospital & Research Centre, Mumbai",
            "batch_number": "ROT-2026-319",
            "vaccination_status": VaccinationStatus.COMPLETED.value,
            "is_verified": True,
        },
        {
            "family_member_id": member_ids["Ananya Sharma"],
            "vaccine_code": "PENTA",
            "vaccine_name": "Pentavalent (DTP-HepB-Hib 2)",
            "dose_number": 2,
            "dose_name": "10 Weeks (Dose 2)",
            "administered_date": datetime(2026, 7, 27),
            "administered_by": "Dr. Anjali Deshmukh",
            "healthcare_provider": "Lilavati Hospital & Research Centre, Mumbai",
            "batch_number": "PNT-2026-441",
            "vaccination_status": VaccinationStatus.COMPLETED.value,
            "is_verified": True,
        },
        {
            "family_member_id": member_ids["Ananya Sharma"],
            "vaccine_code": "OPV",
            "vaccine_name": "Oral Polio Vaccine (OPV-2)",
            "dose_number": 3,
            "dose_name": "10 Weeks (OPV-2)",
            "administered_date": datetime(2026, 7, 27),
            "administered_by": "Dr. Anjali Deshmukh",
            "healthcare_provider": "Lilavati Hospital & Research Centre, Mumbai",
            "batch_number": "OPV-2026-662",
            "vaccination_status": VaccinationStatus.COMPLETED.value,
            "is_verified": True,
        },
        {
            "family_member_id": member_ids["Ananya Sharma"],
            "vaccine_code": "ROTA",
            "vaccine_name": "Rotavirus (RV-2)",
            "dose_number": 2,
            "dose_name": "10 Weeks (Dose 2)",
            "administered_date": datetime(2026, 7, 27),
            "administered_by": "Dr. Anjali Deshmukh",
            "healthcare_provider": "Lilavati Hospital & Research Centre, Mumbai",
            "batch_number": "ROT-2026-773",
            "vaccination_status": VaccinationStatus.COMPLETED.value,
            "is_verified": True,
        },

        # -------------------------------------------------------------
        # POOJA SHARMA (Mother, Adult)
        # -------------------------------------------------------------
        {
            "family_member_id": member_ids["Pooja Sharma"],
            "vaccine_code": "TD",
            "vaccine_name": "Tetanus and adult Diphtheria (Td)",
            "dose_number": 1,
            "dose_name": "Maternal Booster",
            "administered_date": datetime(2026, 2, 10),
            "administered_by": "Dr. Vikram Patil",
            "healthcare_provider": "King Edward Memorial (KEM) Hospital, Mumbai",
            "batch_number": "TD-2026-118",
            "vaccination_status": VaccinationStatus.COMPLETED.value,
            "is_verified": True,
            "notes": "Administered during antenatal evaluation.",
        },

        # -------------------------------------------------------------
        # RAMESH SHARMA (Grandfather, Senior)
        # -------------------------------------------------------------
        {
            "family_member_id": member_ids["Ramesh Sharma"],
            "vaccine_code": "PCV",
            "vaccine_name": "Pneumococcal Conjugate Vaccine (PCV-13)",
            "dose_number": 1,
            "dose_name": "Senior Immunization",
            "administered_date": datetime(2025, 11, 15),
            "administered_by": "Dr. Vikram Patil",
            "healthcare_provider": "King Edward Memorial (KEM) Hospital, Mumbai",
            "batch_number": "PCV-2025-901",
            "vaccination_status": VaccinationStatus.COMPLETED.value,
            "is_verified": True,
            "notes": "Recommended for senior citizens >65 years.",
        },
    ]

    for rec in vaccination_records:
        rec["created_at"] = now_utc
        rec["updated_at"] = now_utc
        query = {
            "family_member_id": rec["family_member_id"],
            "vaccine_code": rec["vaccine_code"],
            "dose_number": rec["dose_number"],
        }
        await db.vaccination_records.update_one(query, {"$set": rec}, upsert=True)
    
    print(f"  Inserted {len(vaccination_records)} verified clinical vaccination records.")

    # 8. Seed Notification Preferences & Live Dynamic Notifications
    print("\n--- 6. Seeding Notification Preferences & Real Notifications ---")
    pref_data = {
        "user_id": patient_id,
        "channels_enabled": [NotificationChannel.IN_APP.value, NotificationChannel.EMAIL.value],
        "reminder_lead_days": [14, 7, 3, 1],
        "email_enabled": True,
        "email_address": patient_email,
        "sms_enabled": True,
        "phone_number": "+919820012345",
        "quiet_hours_enabled": True,
        "quiet_hours_start": "22:00",
        "quiet_hours_end": "08:00",
        "timezone": "Asia/Kolkata",
        "created_at": now_utc,
        "updated_at": now_utc,
    }
    await db.notification_preferences.update_one({"user_id": patient_id}, {"$set": pref_data}, upsert=True)
    print("  Configured notification preferences (Asia/Kolkata timezone, quiet hours 22:00-08:00).")

    # Clean old notifications for this user
    await db.notifications.delete_many({"user_id": patient_id})

    notifications = [
        {
            "user_id": patient_id,
            "family_member_id": member_ids["Aarav Sharma"],
            "member_name": "Aarav Sharma",
            "vaccine_code": "DPT_BOOSTER_2",
            "vaccine_name": "DPT Booster 2 (Age 5-6 Years)",
            "dose_number": 2,
            "dose_name": "DPT Booster 2",
            "due_date": datetime(2026, 7, 10, tzinfo=timezone.utc),
            "vaccination_status": VaccinationStatus.OVERDUE.value,
            "title": "Action Needed: Aarav's DPT Booster 2 is Overdue",
            "message": "Aarav Sharma's DPT Booster 2 (recommended at 5-6 years) was due on 10 July 2026. Please schedule an appointment at Lilavati Hospital or your nearest clinic for catch-up vaccination.",
            "channel": NotificationChannel.IN_APP.value,
            "type": NotificationType.OVERDUE_ALERT.value,
            "priority": NotificationPriority.HIGH.value,
            "status": NotificationStatus.SENT.value,
            "is_read": False,
            "dedup_key": f"{patient_id}_{member_ids['Aarav Sharma']}_DPT_BOOSTER_2_OVERDUE",
            "created_at": now_utc - timedelta(days=2),
            "updated_at": now_utc,
        },
        {
            "user_id": patient_id,
            "family_member_id": member_ids["Ananya Sharma"],
            "member_name": "Ananya Sharma",
            "vaccine_code": "PENTA_3",
            "vaccine_name": "Pentavalent (Dose 3) & OPV (Dose 3)",
            "dose_number": 3,
            "dose_name": "14 Weeks",
            "due_date": datetime(2026, 8, 24, tzinfo=timezone.utc),
            "vaccination_status": VaccinationStatus.CATCH_UP_REQUIRED.value,
            "title": "Milestone Reminder: Ananya's 14-Week Immunization Due",
            "message": "Ananya Sharma's 14-week milestone vaccines (Pentavalent-3, OPV-3, Rotavirus-3, and fractional IPV-2) are due. Please visit Dr. Anjali Deshmukh at Lilavati Hospital.",
            "channel": NotificationChannel.IN_APP.value,
            "type": NotificationType.CATCH_UP_ALERT.value,
            "priority": NotificationPriority.HIGH.value,
            "status": NotificationStatus.SENT.value,
            "is_read": False,
            "dedup_key": f"{patient_id}_{member_ids['Ananya Sharma']}_PENTA_3_CATCHUP",
            "created_at": now_utc - timedelta(days=5),
            "updated_at": now_utc,
        },
        {
            "user_id": patient_id,
            "family_member_id": member_ids["Ramesh Sharma"],
            "member_name": "Ramesh Sharma",
            "vaccine_code": "INFLUENZA_ANNUAL",
            "vaccine_name": "Annual Seasonal Influenza (Quadrivalent)",
            "dose_number": 1,
            "dose_name": "2026-2027 Season",
            "due_date": datetime(2026, 10, 15, tzinfo=timezone.utc),
            "vaccination_status": VaccinationStatus.UPCOMING.value,
            "title": "Upcoming: Senior Citizen Annual Influenza Shot",
            "message": "Ramesh Sharma is eligible for the annual influenza vaccine before the winter respiratory season. Recommended window starts October 15, 2026.",
            "channel": NotificationChannel.EMAIL.value,
            "type": NotificationType.REMINDER.value,
            "priority": NotificationPriority.MEDIUM.value,
            "status": NotificationStatus.SENT.value,
            "is_read": False,
            "dedup_key": f"{patient_id}_{member_ids['Ramesh Sharma']}_FLU_2026",
            "created_at": now_utc - timedelta(days=1),
            "updated_at": now_utc,
        },
        {
            "user_id": patient_id,
            "family_member_id": member_ids["Ananya Sharma"],
            "member_name": "Ananya Sharma",
            "vaccine_code": "PENTA_2",
            "vaccine_name": "Pentavalent Dose 2 Recorded",
            "dose_number": 2,
            "dose_name": "10 Weeks",
            "due_date": datetime(2026, 7, 27, tzinfo=timezone.utc),
            "vaccination_status": VaccinationStatus.COMPLETED.value,
            "title": "Vaccination Verified: Pentavalent-2 & OPV-2",
            "message": "Dr. Anjali Deshmukh has digitally verified and recorded Ananya Sharma's 10-week immunization doses.",
            "channel": NotificationChannel.IN_APP.value,
            "type": NotificationType.STATUS_UPDATE.value,
            "priority": NotificationPriority.LOW.value,
            "status": NotificationStatus.READ.value,
            "is_read": True,
            "read_at": now_utc - timedelta(days=30),
            "dedup_key": f"{patient_id}_{member_ids['Ananya Sharma']}_PENTA_2_COMPLETED",
            "created_at": now_utc - timedelta(days=60),
            "updated_at": now_utc,
        },
    ]

    for n in notifications:
        await db.notifications.insert_one(n)
    print(f"  Inserted {len(notifications)} active and historical notification events.")

    # 9. Verify Final DB Counts
    print("\n--- 7. Database Verification Summary ---")
    cols = ["users", "families", "family_members", "vaccination_records", "notifications", "notification_preferences"]
    for col in cols:
        count = await db[col].count_documents({})
        print(f"  Collection '{col}': {count} records")

    client.close()
    print("\n=======================================================================")
    print("SUCCESS: Phase A Demo Dataset Seeded Successfully!")
    print("=======================================================================")


if __name__ == "__main__":
    asyncio.run(seed_database())
