"""
Centralized, deterministic vaccination schedule catalog based on authoritative sources:
1. Ministry of Health & Family Welfare (MoHFW) — National Immunization Schedule (NIS)
2. National Health Mission (NHM) — Current Universal Immunization Programme (UIP) Schedule
3. World Health Organization (WHO) — India Vaccination Schedule & Country Profile
4. Indian Academy of Pediatrics (IAP) — Advisory Committee on Vaccines and Immunization Practices (ACVIP)

Classifies vaccines strictly into:
- UNIVERSAL_NIS: Government of India routine universal schedule (free at public health facilities)
- CONDITIONAL_NIS: Government of India UIP schedule for designated endemic districts (e.g. JE)
- PRIVATE_OPTIONAL: Non-NIS commercial / pediatric guidelines (e.g. MMR, Tdap, Typhoid, Varicella, HepA, HPV, Influenza)
"""
from typing import List, Dict, Any, Optional
from app.models.vaccination import VaccineCategory

# =============================================================================
# A. UNIVERSAL / ROUTINE NATIONAL IMMUNIZATION SCHEDULE (UIP / NIS)
# =============================================================================

UNIVERSAL_NIS_SCHEDULE: List[Dict[str, Any]] = [
    # 1. BCG
    {
        "code": "BCG",
        "vaccine_code": "BCG",
        "series_code": "BCG",
        "aliases": ["BCG", "BCG_1"],
        "name": "BCG",
        "full_name": "Bacillus Calmette–Guérin vaccine",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 1,
        "dose_name": "Birth Dose",
        "recommended_age_days": 0,
        "recommended_age_display": "At Birth",
        "minimum_age_days": 0,
        "max_age_days": 365,  # Can be given up to 1 year of age when missed
        "can_catch_up": False,
        "catch_up_max_age_days": None,
        "clinical_review_notes": "Exceeds routine UIP limit of 1 year. Under NTEP/MoHFW guidelines, clinical evaluation and Mantoux tuberculin test are required prior to considering BCG vaccination.",
        "minimum_interval_days": None,
        "previous_dose_required": None,
        "due_window_days": 0,
        "grace_period_days": 365,
        "route": "Intradermal",
        "site": "Left upper arm",
        "dose_amount": "0.05 mL until 1 month of age; 0.1 mL after 1 month",
        "target_disease": "Tuberculosis (TB)",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "Administered at birth or as early as possible up to 1 year of age if missed at birth. Single dose, not a multi-dose series.",
    },

    # 2. HEPATITIS B — BIRTH DOSE
    {
        "code": "HEPB_BIRTH",
        "vaccine_code": "HEPB_BIRTH",
        "series_code": "HEPB",
        "aliases": ["HEPB", "HEPATITIS_B", "HEPB_BIRTH", "HEPB_0"],
        "name": "Hepatitis B (Birth Dose)",
        "full_name": "Hepatitis B vaccine — birth dose",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 1,
        "dose_name": "Birth Dose",
        "recommended_age_days": 0,
        "recommended_age_display": "At Birth (within 24 hours)",
        "minimum_age_days": 0,
        "max_age_days": 1,  # Strictly within 24 hours
        "can_catch_up": False,
        "is_strictly_missed_past_window": True,
        "minimum_interval_days": None,
        "previous_dose_required": None,
        "due_window_days": 0,
        "grace_period_days": 1,  # Max 24 hours (1 day)
        "route": "Intramuscular",
        "site": "Anterolateral mid-thigh, left",
        "dose_amount": "0.5 mL",
        "target_disease": "Hepatitis B Virus (perinatal transmission)",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "Must be given within 24 hours of delivery. If missed past 24 hours, do not give birth dose; protection is provided via Pentavalent doses at 6, 10, 14 weeks.",
    },

    # 3. OPV BIRTH DOSE (OPV-0)
    {
        "code": "OPV_0",
        "vaccine_code": "OPV_0",
        "series_code": "OPV",
        "aliases": ["OPV_0", "OPV", "POLIO_0"],
        "name": "Oral Polio Vaccine (OPV-0)",
        "full_name": "Oral Polio Vaccine birth dose",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 1,
        "dose_name": "Zero Dose",
        "recommended_age_days": 0,
        "recommended_age_display": "At Birth (within 15 days)",
        "minimum_age_days": 0,
        "max_age_days": 15,  # Within first 15 days
        "can_catch_up": False,
        "is_strictly_missed_past_window": True,
        "minimum_interval_days": None,
        "previous_dose_required": None,
        "due_window_days": 0,
        "grace_period_days": 15,
        "route": "Oral",
        "site": "Oral",
        "dose_amount": "2 drops",
        "target_disease": "Poliomyelitis",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "Zero dose administered at birth or within the first 15 days before routine series.",
    },

    # 4. OPV-1
    {
        "code": "OPV_1",
        "vaccine_code": "OPV_1",
        "series_code": "OPV",
        "aliases": ["OPV_1", "OPV", "BOPV_1"],
        "name": "Oral Polio Vaccine (OPV-1)",
        "full_name": "Oral Polio Vaccine — Dose 1",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 2,
        "dose_name": "Dose 1",
        "recommended_age_days": 42,
        "recommended_age_display": "6 Weeks",
        "minimum_age_days": 42,
        "max_age_days": 1825,  # Can be given till 5 years
        "minimum_interval_days": 28,
        "previous_dose_required": ("OPV_0", 1),
        "due_window_days": 7,
        "grace_period_days": 28,
        "route": "Oral",
        "site": "Oral",
        "dose_amount": "2 drops",
        "target_disease": "Poliomyelitis",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "First primary OPV dose at 6 weeks. Can be given till 5 years of age.",
        "can_catch_up": True,
        "catch_up_max_age_days": 1825,
        "catch_up_notes": "bOPV can be administered up to 5 years of age under UIP guidelines.",
        "clinical_review_notes": "Exceeds 5 years of age. Routine bOPV is indicated up to 5 years; clinical evaluation required if polio series is incomplete.",
    },

    # 5. PENTAVALENT-1
    {
        "code": "PENTA_1",
        "vaccine_code": "PENTA_1",
        "series_code": "PENTA",
        "aliases": ["PENTA", "PENTAVALENT", "PENTA_1", "DTP_HEPB_HIB_1"],
        "name": "Pentavalent-1",
        "full_name": "Diphtheria + Pertussis + Tetanus + Hepatitis B + Haemophilus influenzae type b",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 1,
        "dose_name": "Dose 1",
        "recommended_age_days": 42,
        "recommended_age_display": "6 Weeks",
        "minimum_age_days": 42,
        "max_age_days": 365,  # Can be given up to 1 year of age
        "minimum_interval_days": None,
        "previous_dose_required": None,
        "due_window_days": 7,
        "grace_period_days": 28,
        "route": "Intramuscular",
        "site": "Anterolateral mid-thigh, left",
        "dose_amount": "0.5 mL",
        "target_disease": "Diphtheria, Pertussis, Tetanus, Hepatitis B, Hib pneumonia/meningitis",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "Combines DTP, HepB, and Hib into a single 5-in-1 injection.",
        "can_catch_up": True,
        "catch_up_max_age_days": 2555,
        "catch_up_notes": "Child has crossed 1 year of age. Under UIP guidelines, Pentavalent formulation is discontinued and catch-up immunization is administered using DPT (up to 7 years) and standalone Hepatitis B doses.",
        "clinical_review_notes": "Child exceeds 7 years of age. DPT/Pentavalent cannot be administered; evaluate for adolescent Td or Tdap.",
    },

    # 6. ROTAVIRUS-1
    {
        "code": "ROTA_1",
        "vaccine_code": "ROTA_1",
        "series_code": "ROTA",
        "aliases": ["ROTA", "ROTAVIRUS", "ROTA_1", "RVV_1"],
        "name": "Rotavirus-1",
        "full_name": "Rotavirus vaccine",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 1,
        "dose_name": "Dose 1",
        "recommended_age_days": 42,
        "recommended_age_display": "6 Weeks",
        "minimum_age_days": 42,
        "max_age_days": 365,
        "minimum_interval_days": None,
        "previous_dose_required": None,
        "due_window_days": 7,
        "grace_period_days": 28,
        "route": "Oral",
        "site": "Oral",
        "dose_amount": "5 drops (Rotavac) / 2.5 mL (Rotasiil)",
        "target_disease": "Rotavirus Diarrheal Disease",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "Oral drops against rotavirus diarrhea. Standard UIP uses 3-dose schedule; formulation depends on product supplied.",
        "can_catch_up": False,
        "is_strictly_missed_past_window": True,
    },

    # 7. FRACTIONAL IPV-1 (fIPV-1)
    {
        "code": "FIPV_1",
        "vaccine_code": "FIPV_1",
        "series_code": "IPV",
        "aliases": ["IPV", "FIPV", "FIPV_1", "IPV_1"],
        "name": "Fractional IPV-1",
        "full_name": "Fractional Inactivated Polio Vaccine",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 1,
        "dose_name": "Dose 1",
        "recommended_age_days": 42,
        "recommended_age_display": "6 Weeks",
        "minimum_age_days": 42,
        "max_age_days": 365,
        "minimum_interval_days": None,
        "previous_dose_required": None,
        "due_window_days": 7,
        "grace_period_days": 28,
        "route": "Intradermal",
        "site": "Right upper arm",
        "dose_amount": "0.1 mL",
        "target_disease": "Poliomyelitis",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "Two drops of OPV plus fractional dose (0.1 mL intradermal) of IPV.",
        "can_catch_up": False,
        "clinical_review_notes": "Exceeds routine UIP infant schedule (< 1 year). Clinical evaluation required to verify polio immunity and complete coverage with bOPV (up to 5 years) or catch-up IPV.",
    },

    # 8. PCV-1
    {
        "code": "PCV_1",
        "vaccine_code": "PCV_1",
        "series_code": "PCV",
        "aliases": ["PCV", "PCV_1", "PNEUMOCOCCAL_1"],
        "name": "PCV-1",
        "full_name": "Pneumococcal Conjugate Vaccine",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 1,
        "dose_name": "Dose 1",
        "recommended_age_days": 42,
        "recommended_age_display": "6 Weeks",
        "minimum_age_days": 42,
        "max_age_days": 365,
        "minimum_interval_days": None,
        "previous_dose_required": None,
        "due_window_days": 7,
        "grace_period_days": 28,
        "route": "Intramuscular",
        "site": "Anterolateral mid-thigh, right",
        "dose_amount": "0.5 mL",
        "target_disease": "Streptococcus pneumoniae (Pneumonia, Meningitis)",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "First primary dose against invasive pneumococcal infection. Universal across India.",
        "can_catch_up": False,
        "clinical_review_notes": "Exceeds routine infant schedule (< 1 year). Clinical review required for high-risk pneumococcal indications.",
    },

    # 9. OPV-2
    {
        "code": "OPV_2",
        "vaccine_code": "OPV_2",
        "series_code": "OPV",
        "aliases": ["OPV_2", "OPV", "BOPV_2"],
        "name": "Oral Polio Vaccine (OPV-2)",
        "full_name": "Oral Polio Vaccine — Dose 2",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 3,
        "dose_name": "Dose 2",
        "recommended_age_days": 70,
        "recommended_age_display": "10 Weeks",
        "minimum_age_days": 70,
        "max_age_days": 1825,
        "minimum_interval_days": 28,
        "previous_dose_required": ("OPV_1", 2),
        "due_window_days": 7,
        "grace_period_days": 28,
        "route": "Oral",
        "site": "Oral",
        "dose_amount": "2 drops",
        "target_disease": "Poliomyelitis",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "Second primary OPV dose (min 4 weeks after Dose 1).",
    },

    # 10. PENTAVALENT-2
    {
        "code": "PENTA_2",
        "vaccine_code": "PENTA_2",
        "series_code": "PENTA",
        "aliases": ["PENTA", "PENTAVALENT", "PENTA_2", "DTP_HEPB_HIB_2"],
        "name": "Pentavalent-2",
        "full_name": "Diphtheria + Pertussis + Tetanus + Hepatitis B + Haemophilus influenzae type b",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 2,
        "dose_name": "Dose 2",
        "recommended_age_days": 70,
        "recommended_age_display": "10 Weeks",
        "minimum_age_days": 70,
        "max_age_days": 365,
        "minimum_interval_days": 28,
        "previous_dose_required": ("PENTA_1", 1),
        "due_window_days": 7,
        "grace_period_days": 28,
        "route": "Intramuscular",
        "site": "Anterolateral mid-thigh, left",
        "dose_amount": "0.5 mL",
        "target_disease": "Diphtheria, Pertussis, Tetanus, Hepatitis B, Hib pneumonia/meningitis",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "Second pentavalent dose (min 4 weeks after Dose 1).",
    },

    # 11. ROTAVIRUS-2
    {
        "code": "ROTA_2",
        "vaccine_code": "ROTA_2",
        "series_code": "ROTA",
        "aliases": ["ROTA", "ROTAVIRUS", "ROTA_2", "RVV_2"],
        "name": "Rotavirus-2",
        "full_name": "Rotavirus vaccine",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 2,
        "dose_name": "Dose 2",
        "recommended_age_days": 70,
        "recommended_age_display": "10 Weeks",
        "minimum_age_days": 70,
        "max_age_days": 365,
        "minimum_interval_days": 28,
        "previous_dose_required": ("ROTA_1", 1),
        "due_window_days": 7,
        "grace_period_days": 28,
        "route": "Oral",
        "site": "Oral",
        "dose_amount": "5 drops (Rotavac) / 2.5 mL (Rotasiil)",
        "target_disease": "Rotavirus Diarrheal Disease",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "Second rotavirus oral dose (min 4 weeks after Dose 1).",
    },

    # 12. OPV-3
    {
        "code": "OPV_3",
        "vaccine_code": "OPV_3",
        "series_code": "OPV",
        "aliases": ["OPV_3", "OPV", "BOPV_3"],
        "name": "Oral Polio Vaccine (OPV-3)",
        "full_name": "Oral Polio Vaccine — Dose 3",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 4,
        "dose_name": "Dose 3",
        "recommended_age_days": 98,
        "recommended_age_display": "14 Weeks",
        "minimum_age_days": 98,
        "max_age_days": 1825,
        "minimum_interval_days": 28,
        "previous_dose_required": ("OPV_2", 3),
        "due_window_days": 7,
        "grace_period_days": 28,
        "route": "Oral",
        "site": "Oral",
        "dose_amount": "2 drops",
        "target_disease": "Poliomyelitis",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "Third primary OPV dose.",
    },

    # 13. PENTAVALENT-3
    {
        "code": "PENTA_3",
        "vaccine_code": "PENTA_3",
        "series_code": "PENTA",
        "aliases": ["PENTA", "PENTAVALENT", "PENTA_3", "DTP_HEPB_HIB_3"],
        "name": "Pentavalent-3",
        "full_name": "Diphtheria + Pertussis + Tetanus + Hepatitis B + Haemophilus influenzae type b",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 3,
        "dose_name": "Dose 3",
        "recommended_age_days": 98,
        "recommended_age_display": "14 Weeks",
        "minimum_age_days": 98,
        "max_age_days": 365,
        "minimum_interval_days": 28,
        "previous_dose_required": ("PENTA_2", 2),
        "due_window_days": 7,
        "grace_period_days": 28,
        "route": "Intramuscular",
        "site": "Anterolateral mid-thigh, left",
        "dose_amount": "0.5 mL",
        "target_disease": "Diphtheria, Pertussis, Tetanus, Hepatitis B, Hib pneumonia/meningitis",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "Third primary pentavalent dose. Completes primary infant series.",
        "can_catch_up": True,
        "catch_up_max_age_days": 2555,
        "catch_up_notes": "Child has crossed 1 year of age. Under UIP guidelines, Pentavalent formulation is discontinued and catch-up immunization is administered using DPT (up to 7 years) and standalone Hepatitis B doses.",
        "clinical_review_notes": "Child exceeds 7 years of age. DPT/Pentavalent cannot be administered; evaluate for adolescent Td or Tdap.",
    },

    # 14. ROTAVIRUS-3
    {
        "code": "ROTA_3",
        "vaccine_code": "ROTA_3",
        "series_code": "ROTA",
        "aliases": ["ROTA", "ROTAVIRUS", "ROTA_3", "RVV_3"],
        "name": "Rotavirus-3",
        "full_name": "Rotavirus vaccine",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 3,
        "dose_name": "Dose 3",
        "recommended_age_days": 98,
        "recommended_age_display": "14 Weeks",
        "minimum_age_days": 98,
        "max_age_days": 365,
        "minimum_interval_days": 28,
        "previous_dose_required": ("ROTA_2", 2),
        "due_window_days": 7,
        "grace_period_days": 28,
        "route": "Oral",
        "site": "Oral",
        "dose_amount": "5 drops (Rotavac) / 2.5 mL (Rotasiil)",
        "target_disease": "Rotavirus Diarrheal Disease",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "Third rotavirus dose completing primary infant diarrhea protection.",
        "can_catch_up": False,
        "is_strictly_missed_past_window": True,
    },

    # 15. FRACTIONAL IPV-2 (fIPV-2)
    {
        "code": "FIPV_2",
        "vaccine_code": "FIPV_2",
        "series_code": "IPV",
        "aliases": ["IPV", "FIPV", "FIPV_2", "IPV_2"],
        "name": "Fractional IPV-2",
        "full_name": "Fractional Inactivated Polio Vaccine",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 2,
        "dose_name": "Dose 2",
        "recommended_age_days": 98,
        "recommended_age_display": "14 Weeks",
        "minimum_age_days": 98,
        "max_age_days": 365,
        "minimum_interval_days": 56,  # 8 weeks after fIPV-1
        "previous_dose_required": ("FIPV_1", 1),
        "due_window_days": 7,
        "grace_period_days": 28,
        "route": "Intradermal",
        "site": "Right upper arm",
        "dose_amount": "0.1 mL",
        "target_disease": "Poliomyelitis",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "Second fractional IPV dose at 14 weeks.",
        "can_catch_up": False,
        "clinical_review_notes": "Exceeds routine UIP infant schedule (< 1 year). Clinical evaluation required to verify polio immunity and complete coverage with bOPV (up to 5 years) or catch-up IPV.",
    },

    # 16. PCV-2
    {
        "code": "PCV_2",
        "vaccine_code": "PCV_2",
        "series_code": "PCV",
        "aliases": ["PCV", "PCV_2", "PNEUMOCOCCAL_2"],
        "name": "PCV-2",
        "full_name": "Pneumococcal Conjugate Vaccine",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 2,
        "dose_name": "Dose 2",
        "recommended_age_days": 98,
        "recommended_age_display": "14 Weeks",
        "minimum_age_days": 98,
        "max_age_days": 365,
        "minimum_interval_days": 56,  # 8 weeks after PCV-1
        "previous_dose_required": ("PCV_1", 1),
        "due_window_days": 7,
        "grace_period_days": 28,
        "route": "Intramuscular",
        "site": "Anterolateral mid-thigh, right",
        "dose_amount": "0.5 mL",
        "target_disease": "Streptococcus pneumoniae (Pneumonia, Meningitis)",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "Second primary PCV dose.",
    },

    # 17. FRACTIONAL IPV-3 (fIPV-3) — Confirmed 2023 MoHFW UIP Mandate
    {
        "code": "FIPV_3",
        "vaccine_code": "FIPV_3",
        "series_code": "IPV",
        "aliases": ["IPV", "FIPV", "FIPV_3", "IPV_3"],
        "name": "Fractional IPV-3",
        "full_name": "Fractional Inactivated Polio Vaccine",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 3,
        "dose_name": "Dose 3",
        "recommended_age_days": 270,
        "recommended_age_display": "9–12 Months",
        "minimum_age_days": 270,
        "max_age_days": 365,
        "minimum_interval_days": 112,  # 16 weeks after fIPV-2
        "previous_dose_required": ("FIPV_2", 2),
        "due_window_days": 14,
        "grace_period_days": 60,
        "route": "Intradermal",
        "site": "Left upper arm",
        "dose_amount": "0.1 mL",
        "target_disease": "Poliomyelitis",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP (w.e.f. Jan 1, 2023)",
        "notes": "Introduced effective January 1, 2023 by MoHFW. Administered at 9 completed months with MR-1 to enhance mucosal and humoral polio immunity.",
        "can_catch_up": False,
        "clinical_review_notes": "Exceeds routine UIP infant schedule (< 1 year). Clinical evaluation required to verify polio immunity and complete coverage with bOPV (up to 5 years) or catch-up IPV.",
    },

    # 18. PCV BOOSTER
    {
        "code": "PCV_BOOSTER",
        "vaccine_code": "PCV_BOOSTER",
        "series_code": "PCV",
        "aliases": ["PCV", "PCV_3", "PCV_BOOSTER", "PNEUMOCOCCAL_BOOSTER"],
        "name": "PCV Booster",
        "full_name": "Pneumococcal Conjugate Vaccine Booster",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 3,
        "dose_name": "Booster",
        "recommended_age_days": 270,
        "recommended_age_display": "9–12 Months",
        "minimum_age_days": 270,
        "max_age_days": 730,
        "minimum_interval_days": 120,
        "previous_dose_required": ("PCV_2", 2),
        "due_window_days": 14,
        "grace_period_days": 60,
        "route": "Intramuscular",
        "site": "Anterolateral mid-thigh, right",
        "dose_amount": "0.5 mL",
        "target_disease": "Streptococcus pneumoniae (Pneumonia, Meningitis)",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "PCV booster dose at 9 completed months.",
    },

    # 19. MR-1 (Measles-Rubella 1)
    {
        "code": "MR_1",
        "vaccine_code": "MR_1",
        "series_code": "MR",
        "aliases": ["MR", "MR_1", "MEASLES_1", "MEASLES_RUBELLA_1", "MMR", "MMR_1"],
        "name": "MR-1",
        "full_name": "Measles-Rubella vaccine",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 1,
        "dose_name": "Dose 1",
        "recommended_age_days": 270,
        "recommended_age_display": "9–12 Months",
        "minimum_age_days": 270,
        "max_age_days": 1825,  # Routine upper limit: 5 years
        "can_catch_up": True,
        "catch_up_max_age_days": 5475,  # Catch-up up to 15 years under MoHFW/WHO guidelines
        "minimum_interval_days": None,
        "previous_dose_required": None,
        "due_window_days": 14,
        "grace_period_days": 60,
        "route": "Subcutaneous",
        "site": "Right upper arm",
        "dose_amount": "0.5 mL",
        "target_disease": "Measles, Rubella",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "Government UIP provides MR (Measles-Rubella), NOT MMR. Given at 9 completed months to 12 months. Routine till 5 years, catch-up up to 15 years.",
        "catch_up_notes": "Child has exceeded the routine 5-year UIP window. Under MoHFW and WHO India guidelines, MR catch-up vaccination can and should be administered up to 15 years of age.",
        "clinical_review_notes": "Exceeds 15 years of age. Clinical evaluation required for adolescent/adult measles-rubella immunization.",
    },

    # 20. MR-2 (Measles-Rubella 2)
    {
        "code": "MR_2",
        "vaccine_code": "MR_2",
        "series_code": "MR",
        "aliases": ["MR", "MR_2", "MEASLES_2", "MEASLES_RUBELLA_2", "MMR", "MMR_2"],
        "name": "MR-2",
        "full_name": "Measles-Rubella vaccine",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 2,
        "dose_name": "Dose 2",
        "recommended_age_days": 480,
        "recommended_age_display": "16–24 Months",
        "minimum_age_days": 480,
        "max_age_days": 1825,  # Routine upper limit: 5 years
        "can_catch_up": True,
        "catch_up_max_age_days": 5475,  # Catch-up up to 15 years
        "minimum_interval_days": 28,
        "previous_dose_required": ("MR_1", 1),
        "due_window_days": 30,
        "grace_period_days": 90,
        "route": "Subcutaneous",
        "site": "Right upper arm",
        "dose_amount": "0.5 mL",
        "target_disease": "Measles, Rubella",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "Second MR dose at 16–24 months. Routine till 5 years, catch-up up to 15 years.",
        "catch_up_notes": "Child has exceeded the routine 5-year UIP window. Under MoHFW and WHO India guidelines, MR-2 catch-up vaccination can and should be administered up to 15 years of age.",
        "clinical_review_notes": "Exceeds 15 years of age. Clinical evaluation required for adolescent/adult measles-rubella immunization.",
    },

    # 21. DPT BOOSTER-1
    {
        "code": "DPT_BOOSTER_1",
        "vaccine_code": "DPT_BOOSTER_1",
        "series_code": "DPT",
        "aliases": ["DPT", "DTP", "DPT_1", "DTP_1", "DPT_BOOSTER_1", "DTP_BOOSTER_1"],
        "name": "DPT Booster-1",
        "full_name": "Diphtheria + Pertussis + Tetanus",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 1,
        "dose_name": "Booster 1",
        "recommended_age_days": 480,
        "recommended_age_display": "16–24 Months",
        "minimum_age_days": 480,
        "max_age_days": 2555,  # Routine upper limit: 7 years
        "can_catch_up": True,
        "catch_up_max_age_days": 5840,  # Catch-up with Td if >7 years
        "minimum_interval_days": 180,  # 6 months after Penta-3
        "previous_dose_required": ("PENTA_3", 3),
        "due_window_days": 30,
        "grace_period_days": 90,
        "route": "Intramuscular",
        "site": "Anterolateral mid-thigh, left",
        "dose_amount": "0.5 mL",
        "target_disease": "Diphtheria, Pertussis, Tetanus",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "First DPT booster following completion of primary pentavalent series. Can be given till 7 years.",
        "catch_up_notes": "Child is older than 7 years. Whole-cell pertussis (wP) in DPT is contraindicated past 7 years; catch-up must be administered using adult Td or Tdap.",
        "clinical_review_notes": "Exceeds 16 years. Clinical evaluation for adult Td/Tdap booster.",
    },

    # 22. OPV BOOSTER
    {
        "code": "OPV_BOOSTER",
        "vaccine_code": "OPV_BOOSTER",
        "series_code": "OPV",
        "aliases": ["OPV", "OPV_BOOSTER", "BOPV_BOOSTER", "OPV_4", "OPV_5"],
        "name": "Oral Polio Vaccine Booster",
        "full_name": "Oral Polio Vaccine Booster dose",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 5,
        "dose_name": "Booster",
        "recommended_age_days": 480,
        "recommended_age_display": "16–24 Months",
        "minimum_age_days": 480,
        "max_age_days": 1825,  # Up to 5 years
        "can_catch_up": True,
        "catch_up_max_age_days": 1825,
        "minimum_interval_days": 180,
        "previous_dose_required": ("OPV_3", 4),
        "due_window_days": 30,
        "grace_period_days": 90,
        "route": "Oral",
        "site": "Oral",
        "dose_amount": "2 drops",
        "target_disease": "Poliomyelitis",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "OPV booster given alongside DPT Booster-1 at 16–24 months.",
        "catch_up_notes": "bOPV booster can be administered up to 5 years of age.",
        "clinical_review_notes": "Exceeds 5 years of age. Routine bOPV is indicated up to 5 years.",
    },

    # 23. DPT BOOSTER-2
    {
        "code": "DPT_BOOSTER_2",
        "vaccine_code": "DPT_BOOSTER_2",
        "series_code": "DPT",
        "aliases": ["DPT", "DTP", "DPT_2", "DTP_2", "DPT_BOOSTER_2", "DTP_BOOSTER_2"],
        "name": "DPT Booster-2",
        "full_name": "Diphtheria + Pertussis + Tetanus",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 2,
        "dose_name": "Booster 2",
        "recommended_age_days": 1825,
        "recommended_age_display": "5–6 Years",
        "minimum_age_days": 1825,
        "max_age_days": 2555,  # Upper limit: 7 years
        "can_catch_up": True,
        "catch_up_max_age_days": 5840,
        "minimum_interval_days": 365,
        "previous_dose_required": ("DPT_BOOSTER_1", 1),
        "due_window_days": 60,
        "grace_period_days": 180,
        "route": "Intramuscular",
        "site": "Upper arm",
        "dose_amount": "0.5 mL",
        "target_disease": "Diphtheria, Pertussis, Tetanus",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "Second DPT booster administered before school entry. Not given after 7 years of age (Td is used instead).",
        "catch_up_notes": "Child is older than 7 years. Whole-cell pertussis (wP) in DPT is contraindicated past 7 years; catch-up must be administered using adult Td or Tdap.",
        "clinical_review_notes": "Exceeds 16 years. Clinical evaluation for adult Td/Tdap booster.",
    },

    # 24. Td-10 (Tetanus & adult Diphtheria at 10 years)
    {
        "code": "TD_10Y",
        "vaccine_code": "TD_10Y",
        "series_code": "TD",
        "aliases": ["TD", "TD_10", "TD_10Y", "TT", "TT_10", "TDAP"],
        "name": "Td-10",
        "full_name": "Tetanus and adult Diphtheria vaccine",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 1,
        "dose_name": "10-Year Dose",
        "recommended_age_days": 3650,
        "recommended_age_display": "10 Years",
        "minimum_age_days": 3650,
        "max_age_days": None,  # Td has no upper age limit; adults can receive Td at any age
        "can_catch_up": True,
        "catch_up_max_age_days": None,
        "minimum_interval_days": None,
        "previous_dose_required": None,
        "due_window_days": 90,
        "grace_period_days": 365,
        "route": "Intramuscular",
        "site": "Upper arm",
        "dose_amount": "0.5 mL",
        "target_disease": "Tetanus, Diphtheria",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP (Replaced TT)",
        "notes": "Official UIP vaccine replacing TT in 2018–2019 to sustain adult diphtheria immunity. Td has no upper age limit.",
        "catch_up_notes": "Td has no upper age limit. If overdue, administer 0.5 mL IM as early as possible.",
    },

    # 25. Td-16 (Tetanus & adult Diphtheria at 16 years)
    {
        "code": "TD_16Y",
        "vaccine_code": "TD_16Y",
        "series_code": "TD",
        "aliases": ["TD", "TD_16", "TD_16Y", "TT", "TT_16", "TDAP"],
        "name": "Td-16",
        "full_name": "Tetanus and adult Diphtheria vaccine",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 2,
        "dose_name": "16-Year Dose",
        "recommended_age_days": 5840,
        "recommended_age_display": "16 Years",
        "minimum_age_days": 5840,
        "max_age_days": None,  # Td has no upper age limit
        "can_catch_up": True,
        "catch_up_max_age_days": None,
        "minimum_interval_days": 365,
        "previous_dose_required": ("TD_10Y", 1),
        "due_window_days": 90,
        "grace_period_days": 365,
        "route": "Intramuscular",
        "site": "Upper arm",
        "dose_amount": "0.5 mL",
        "target_disease": "Tetanus, Diphtheria",
        "is_conditional": False,
        "source_guideline": "MoHFW National Immunization Schedule / UIP (Replaced TT)",
        "notes": "Official UIP adolescent booster at 16 years. Td has no upper age limit.",
        "catch_up_notes": "Td has no upper age limit. If overdue, administer 0.5 mL IM as early as possible.",
    },

    # 26. Td FOR PREGNANCY (Contextual, tracked separately from child schedule)
    {
        "code": "TD_PREGNANCY",
        "vaccine_code": "TD_PREGNANCY",
        "series_code": "TD_PREG",
        "aliases": ["TD_PREGNANCY", "TD_PREG", "TT_PREGNANCY"],
        "name": "Td for Pregnancy",
        "full_name": "Tetanus and adult Diphtheria vaccine for pregnant women",
        "category": VaccineCategory.UNIVERSAL_NIS.value,
        "dose_number": 1,
        "dose_name": "Td-1 / Td-2 / Booster",
        "recommended_age_days": 0,
        "recommended_age_display": "During Pregnancy",
        "minimum_age_days": 0,
        "max_age_days": None,
        "minimum_interval_days": 28,  # Td-2 is 4 weeks after Td-1
        "previous_dose_required": None,
        "due_window_days": 0,
        "grace_period_days": 270,
        "route": "Intramuscular",
        "site": "Upper arm",
        "dose_amount": "0.5 mL",
        "target_disease": "Maternal and Neonatal Tetanus, Diphtheria",
        "is_conditional": True,
        "is_contextual_pregnancy": True,
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "Administered during pregnancy: Td-1 early in pregnancy, Td-2 4 weeks later; or single Td booster if received 2 Td doses in a pregnancy within the last 3 years.",
    },
]


# =============================================================================
# B. CONDITIONAL NATIONAL IMMUNIZATION SCHEDULE (CONDITIONAL_NIS)
# =============================================================================

CONDITIONAL_NIS_SCHEDULE: List[Dict[str, Any]] = [
    # 27. JE-1 (Japanese Encephalitis 1)
    {
        "code": "JE_1",
        "vaccine_code": "JE_1",
        "series_code": "JE",
        "aliases": ["JE", "JE_1", "JAPANESE_ENCEPHALITIS_1"],
        "name": "JE-1",
        "full_name": "Japanese Encephalitis vaccine",
        "category": VaccineCategory.CONDITIONAL_NIS.value,
        "dose_number": 1,
        "dose_name": "Dose 1",
        "recommended_age_days": 270,
        "recommended_age_display": "9–12 Months",
        "minimum_age_days": 270,
        "max_age_days": 1825,  # Up to 5 years routine
        "can_catch_up": True,
        "catch_up_max_age_days": 5475,  # Catch-up up to 15 years in endemic districts
        "minimum_interval_days": None,
        "previous_dose_required": None,
        "due_window_days": 14,
        "grace_period_days": 60,
        "route": "Subcutaneous",
        "site": "Left upper arm",
        "dose_amount": "0.5 mL",
        "target_disease": "Japanese Encephalitis",
        "is_conditional": True,
        "condition_tag": "eligible_for_je",
        "condition_description": "Applicable only in ~231 designated Japanese Encephalitis endemic districts across India under UIP.",
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "Live attenuated SA-14-14-2 vaccine administered in designated endemic districts alongside MR-1. Not universal for all districts.",
        "catch_up_notes": "In endemic districts under UIP, children who missed the 9–12 month dose can receive JE catch-up vaccination up to 15 years of age.",
        "clinical_review_notes": "Age exceeds 15 years. Clinical evaluation required for JE vaccination in individuals residing in endemic districts.",
    },

    # 28. JE-2 (Japanese Encephalitis 2)
    {
        "code": "JE_2",
        "vaccine_code": "JE_2",
        "series_code": "JE",
        "aliases": ["JE", "JE_2", "JAPANESE_ENCEPHALITIS_2"],
        "name": "JE-2",
        "full_name": "Japanese Encephalitis vaccine",
        "category": VaccineCategory.CONDITIONAL_NIS.value,
        "dose_number": 2,
        "dose_name": "Dose 2",
        "recommended_age_days": 480,
        "recommended_age_display": "16–24 Months",
        "minimum_age_days": 480,
        "max_age_days": 1825,  # Up to 5 years routine
        "can_catch_up": True,
        "catch_up_max_age_days": 5475,  # Catch-up up to 15 years in endemic districts
        "minimum_interval_days": 28,  # MoHFW/ITSU operational guidelines: Minimum 28 days (4 weeks / 1 month) interval when delayed, provided child is at least 16 months of age
        "previous_dose_required": ("JE_1", 1),
        "due_window_days": 30,
        "grace_period_days": 90,
        "route": "Subcutaneous",
        "site": "Left upper arm",
        "dose_amount": "0.5 mL",
        "target_disease": "Japanese Encephalitis",
        "is_conditional": True,
        "condition_tag": "eligible_for_je",
        "condition_description": "Applicable only in ~231 designated Japanese Encephalitis endemic districts across India under UIP.",
        "source_guideline": "MoHFW National Immunization Schedule / UIP",
        "notes": "Second JE dose at 16–24 months in endemic districts. If delayed, minimum interval is 1 month (28 days) after JE-1, provided minimum age 16 months is reached.",
        "catch_up_notes": "In endemic districts, second JE dose can be administered up to 15 years of age with a minimum interval of 28 days after JE-1.",
        "clinical_review_notes": "Age exceeds 15 years. Clinical evaluation required.",
    },
]


# =============================================================================
# C. PRIVATE / OPTIONAL / IAP-STYLE VACCINES (PRIVATE_OPTIONAL)
# =============================================================================

PRIVATE_OPTIONAL_SCHEDULE: List[Dict[str, Any]] = [
    # 29. MMR (Measles, Mumps, Rubella)
    {
        "code": "MMR",
        "vaccine_code": "MMR",
        "series_code": "MMR",
        "aliases": ["MMR", "MMR_1", "MMR_2"],
        "name": "MMR",
        "full_name": "Measles, Mumps and Rubella vaccine",
        "category": VaccineCategory.PRIVATE_OPTIONAL.value,
        "dose_number": 1,
        "dose_name": "IAP Dose",
        "recommended_age_days": 270,
        "recommended_age_display": "9 Months & 15 Months",
        "minimum_age_days": 270,
        "max_age_days": 4380,
        "minimum_interval_days": 28,
        "previous_dose_required": None,
        "due_window_days": 30,
        "grace_period_days": 90,
        "route": "Subcutaneous",
        "site": "Upper arm",
        "dose_amount": "0.5 mL",
        "target_disease": "Measles, Mumps, Rubella",
        "is_conditional": False,
        "source_guideline": "Indian Academy of Pediatrics (IAP) Immunization Timetable",
        "notes": "Private / IAP optional vaccine covering Mumps. Not part of Universal NIS where MR is provided without the mumps antigen.",
    },

    # 30. TDAP (Tetanus, reduced diphtheria, acellular pertussis)
    {
        "code": "TDAP",
        "vaccine_code": "TDAP",
        "series_code": "TDAP",
        "aliases": ["TDAP", "TDAP_10"],
        "name": "Tdap",
        "full_name": "Tetanus toxoid + reduced diphtheria toxoid + acellular pertussis",
        "category": VaccineCategory.PRIVATE_OPTIONAL.value,
        "dose_number": 1,
        "dose_name": "Adolescent Booster",
        "recommended_age_days": 3650,
        "recommended_age_display": "10 Years / Adolescent",
        "minimum_age_days": 3650,
        "max_age_days": 6570,
        "minimum_interval_days": None,
        "previous_dose_required": None,
        "due_window_days": 90,
        "grace_period_days": 365,
        "route": "Intramuscular",
        "site": "Upper arm (Deltoid)",
        "dose_amount": "0.5 mL",
        "target_disease": "Tetanus, Diphtheria, Pertussis (Whooping cough)",
        "is_conditional": False,
        "source_guideline": "Indian Academy of Pediatrics (IAP) Immunization Timetable",
        "notes": "Private / IAP alternative providing acellular pertussis protection at 10 years. Not part of Universal NIS where Td is provided.",
    },

    # 31. TYPHOID CONJUGATE VACCINE (TCV)
    {
        "code": "TYPHOID",
        "vaccine_code": "TYPHOID",
        "series_code": "TYPHOID",
        "aliases": ["TYPHOID", "TCV", "TYPHOID_CONJUGATE"],
        "name": "Typhoid Conjugate Vaccine",
        "full_name": "Typhoid Conjugate Vaccine (TCV)",
        "category": VaccineCategory.PRIVATE_OPTIONAL.value,
        "dose_number": 1,
        "dose_name": "Primary Dose",
        "recommended_age_days": 180,
        "recommended_age_display": "6–9 Months",
        "minimum_age_days": 180,
        "max_age_days": 5840,
        "minimum_interval_days": None,
        "previous_dose_required": None,
        "due_window_days": 30,
        "grace_period_days": 180,
        "route": "Intramuscular",
        "site": "Anterolateral mid-thigh or Deltoid",
        "dose_amount": "0.5 mL",
        "target_disease": "Salmonella Typhi (Typhoid Fever)",
        "is_conditional": False,
        "source_guideline": "Indian Academy of Pediatrics (IAP) Immunization Timetable",
        "notes": "Single dose TCV recommended by IAP from 6–9 months onwards. Long-lasting conjugate protection. Not in Universal NIS.",
    },

    # 32. VARICELLA (Chickenpox)
    {
        "code": "VARICELLA",
        "vaccine_code": "VARICELLA",
        "series_code": "VARICELLA",
        "aliases": ["VARICELLA", "CHICKENPOX", "VARICELLA_1", "VARICELLA_2"],
        "name": "Varicella Vaccine",
        "full_name": "Varicella (Chickenpox) vaccine",
        "category": VaccineCategory.PRIVATE_OPTIONAL.value,
        "dose_number": 1,
        "dose_name": "Dose 1",
        "recommended_age_days": 450,
        "recommended_age_display": "15 Months & 4–6 Years",
        "minimum_age_days": 365,
        "max_age_days": 4380,
        "minimum_interval_days": 84,  # Min 3 months between doses
        "previous_dose_required": None,
        "due_window_days": 30,
        "grace_period_days": 180,
        "route": "Subcutaneous",
        "site": "Upper arm",
        "dose_amount": "0.5 mL",
        "target_disease": "Varicella Zoster Virus (Chickenpox)",
        "is_conditional": False,
        "source_guideline": "Indian Academy of Pediatrics (IAP) Immunization Timetable",
        "notes": "IAP 2-dose schedule (Dose 1 at 15 months, Dose 2 at 4–6 years). Not part of Universal NIS.",
    },

    # 33. HEPATITIS A
    {
        "code": "HEPA",
        "vaccine_code": "HEPA",
        "series_code": "HEPA",
        "aliases": ["HEPA", "HEPATITIS_A", "HEPA_1", "HEPA_2"],
        "name": "Hepatitis A Vaccine",
        "full_name": "Hepatitis A vaccine",
        "category": VaccineCategory.PRIVATE_OPTIONAL.value,
        "dose_number": 1,
        "dose_name": "Primary Dose",
        "recommended_age_days": 365,
        "recommended_age_display": "12 Months onwards",
        "minimum_age_days": 365,
        "max_age_days": 5840,
        "minimum_interval_days": 180,
        "previous_dose_required": None,
        "due_window_days": 30,
        "grace_period_days": 180,
        "route": "Intramuscular or Subcutaneous",
        "site": "Deltoid muscle",
        "dose_amount": "0.5 mL (product-dependent)",
        "target_disease": "Hepatitis A Virus",
        "is_conditional": False,
        "source_guideline": "Indian Academy of Pediatrics (IAP) Immunization Timetable",
        "notes": "Live attenuated (single dose at 12 months) or inactivated (2 doses at 0 and 6 months). Product-dependent. Not in Universal NIS.",
    },

    # 34. HPV (Human Papillomavirus)
    {
        "code": "HPV",
        "vaccine_code": "HPV",
        "series_code": "HPV",
        "aliases": ["HPV", "CERVARIX", "GARDASIL", "HPV_1", "HPV_2"],
        "name": "HPV Vaccine",
        "full_name": "Human Papillomavirus vaccine",
        "category": VaccineCategory.PRIVATE_OPTIONAL.value,
        "dose_number": 1,
        "dose_name": "Adolescent Dose 1",
        "recommended_age_days": 3285,  # 9 years
        "recommended_age_display": "9–14 Years",
        "minimum_age_days": 3285,
        "max_age_days": 9490,  # up to 26 years
        "minimum_interval_days": 180,  # 6 months for 2-dose series
        "previous_dose_required": None,
        "due_window_days": 90,
        "grace_period_days": 365,
        "route": "Intramuscular",
        "site": "Deltoid muscle",
        "dose_amount": "0.5 mL",
        "target_disease": "Human Papillomavirus (Cervical and Anogenital cancers)",
        "is_conditional": False,
        "source_guideline": "Indian Academy of Pediatrics (IAP) Immunization Timetable",
        "notes": "For adolescents aged 9–14 years, a 2-dose schedule (0 and 6 months) is recommended. Aged 15+ years requires 3 doses (0, 1-2, 6 months). Not yet universally rolled out in NIS.",
    },

    # 35. INFLUENZA (Annual / Seasonal)
    {
        "code": "INFLUENZA",
        "vaccine_code": "INFLUENZA",
        "series_code": "INFLUENZA",
        "aliases": ["INFLUENZA", "FLU", "INFLUENZA_ANNUAL"],
        "name": "Influenza Vaccine (Seasonal)",
        "full_name": "Influenza vaccine",
        "category": VaccineCategory.PRIVATE_OPTIONAL.value,
        "dose_number": 1,
        "dose_name": "Annual Dose",
        "recommended_age_days": 180,
        "recommended_age_display": "From 6 Months (Annual)",
        "minimum_age_days": 180,
        "max_age_days": None,
        "minimum_interval_days": 28,
        "previous_dose_required": None,
        "due_window_days": 30,
        "grace_period_days": 180,
        "route": "Intramuscular",
        "site": "Anterolateral thigh / Deltoid",
        "dose_amount": "0.5 mL (product-dependent)",
        "target_disease": "Seasonal Influenza Virus strains",
        "is_conditional": False,
        "is_recurring_annual": True,
        "source_guideline": "Indian Academy of Pediatrics (IAP) Immunization Timetable",
        "notes": "Annual recurring seasonal immunization beginning at 6 months of age. Children <9 years receiving for the first time require 2 doses 4 weeks apart. Not part of Universal NIS.",
    },
]

# Combined Complete Catalog
ALL_VACCINE_CATALOG: List[Dict[str, Any]] = (
    UNIVERSAL_NIS_SCHEDULE + CONDITIONAL_NIS_SCHEDULE + PRIVATE_OPTIONAL_SCHEDULE
)

# Standard Universal Schedule for child dashboard (excluding contextual pregnancy entry by default)
STANDARD_VACCINATION_SCHEDULE: List[Dict[str, Any]] = [
    item for item in UNIVERSAL_NIS_SCHEDULE if not item.get("is_contextual_pregnancy")
]


def get_catalog(
    category: Optional[str] = None,
    eligible_for_je: bool = False,
    include_private_optional: bool = False,
) -> List[Dict[str, Any]]:
    """
    Returns filtered vaccine catalog entries according to category or clinical eligibility.
    """
    if category:
        cat_upper = category.strip().upper()
        return [item for item in ALL_VACCINE_CATALOG if item["category"] == cat_upper]

    # Dynamic assembly
    results = [item for item in UNIVERSAL_NIS_SCHEDULE if not item.get("is_contextual_pregnancy")]
    if eligible_for_je:
        results.extend(CONDITIONAL_NIS_SCHEDULE)
    if include_private_optional:
        results.extend(PRIVATE_OPTIONAL_SCHEDULE)

    return results
